### ISSUE TITLE
Font/Text Not Appearing

### ISSUE THREAD

**Issue by nicktgbrown** [nicktgbrown/modularity-mindfulness#1]
I'm not sure what has happened, by (only within Markbot's comparison between my code and screenshots) my font is not appearing. It's taking up the correct amount of space, yet it is not visible.

<img width="316" alt="screen shot 2017-09-14 at 11 08 10 am" src="https://user-images.githubusercontent.com/25106751/30437609-08ed4550-993d-11e7-9f5b-55360a3f4822.png">

I've checked all the font references in my html and css and they seem to be fine.

@hellachella

**Comment by hellachella** [comment]
Hi @nicktgbrown 

They do seem to be fine. I've cloned your repository and opened it in my browser and the text is showing up fine. 

One thing to try is putting your Japanese text within `<i>` tags.  You will also have to specify that the language is Japanese which might be why Markbot isn't accepting it.

`<i class="text-center yotta push-1-2 not-bold lang="ja">自然の親密な本質を模倣し、人生の真の意味を発見する。</i>`

You should also add a class of 'not-italic' and larger gutters on the left and right.

Let me know how this goes.
